from forms.province_form import ProvinceForm
from forms.cooperative_form import CooperativeForm
from forms.categorie_form import CategorieForm
from forms.actif_form import ActifForm
from forms.finance_form import FinanceForm
from forms.history_form import History_FinanceForm
from forms.project_form import ProjectForm
from forms.evolution_form import EvolutionForm
from forms.membre_form import MembreForm
from forms.personnel_form import PersonnelForm
from forms.progres_form import ProgresForm